// <auto-generated />
using System;
using Kinopoisk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240601065841_RenamedWatchedMoviesTable")]
    partial class RenamedWatchedMoviesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kinopoisk.Models.CountryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("MovieInfoModelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MovieInfoModelId");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("Kinopoisk.Models.GenreModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("MovieInfoModelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MovieInfoModelId");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("Kinopoisk.Models.MovieCountryModel", b =>
                {
                    b.Property<Guid>("CountryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("country_id");

                    b.Property<Guid>("MovieInfoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movie_info_id");

                    b.HasIndex("CountryId");

                    b.HasIndex("MovieInfoId");

                    b.ToTable("movies_countries");
                });

            modelBuilder.Entity("Kinopoisk.Models.MovieGenreModel", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("char(36)")
                        .HasColumnName("genre_id");

                    b.Property<Guid>("MovieInfoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movie_info_id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieInfoId");

                    b.ToTable("movies_genres");
                });

            modelBuilder.Entity("Kinopoisk.Models.MovieInfoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("KinopoiskId")
                        .HasColumnType("int")
                        .HasColumnName("kinopoisk_id");

                    b.Property<string>("NameEn")
                        .HasColumnType("longtext")
                        .HasColumnName("name_en");

                    b.Property<string>("NameOriginal")
                        .HasColumnType("longtext")
                        .HasColumnName("name_original");

                    b.Property<string>("NameRu")
                        .HasColumnType("longtext")
                        .HasColumnName("name_ru");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("poster_url");

                    b.Property<string>("PosterUrlPreview")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("poster_url_preview");

                    b.Property<double?>("RatingKinopoisk")
                        .HasColumnType("double")
                        .HasColumnName("rating_kinopoisk");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("movie_infos");
                });

            modelBuilder.Entity("Kinopoisk.Models.MovieModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("MovieInfoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movie_info_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("uri");

                    b.HasKey("Id");

                    b.HasIndex("MovieInfoId")
                        .IsUnique();

                    b.ToTable("movies");
                });

            modelBuilder.Entity("Kinopoisk.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_authorized");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_digest");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WatchedMovieModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("char(36)")
                        .HasColumnName("movie_id");

                    b.Property<int>("TimeStamp")
                        .HasColumnType("int")
                        .HasColumnName("time_stamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("watched_movies");
                });

            modelBuilder.Entity("Kinopoisk.Models.CountryModel", b =>
                {
                    b.HasOne("Kinopoisk.Models.MovieInfoModel", null)
                        .WithMany("Countries")
                        .HasForeignKey("MovieInfoModelId");
                });

            modelBuilder.Entity("Kinopoisk.Models.GenreModel", b =>
                {
                    b.HasOne("Kinopoisk.Models.MovieInfoModel", null)
                        .WithMany("Genres")
                        .HasForeignKey("MovieInfoModelId");
                });

            modelBuilder.Entity("Kinopoisk.Models.MovieCountryModel", b =>
                {
                    b.HasOne("Kinopoisk.Models.CountryModel", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kinopoisk.Models.MovieInfoModel", "MovieInfo")
                        .WithMany()
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("MovieInfo");
                });

            modelBuilder.Entity("Kinopoisk.Models.MovieGenreModel", b =>
                {
                    b.HasOne("Kinopoisk.Models.GenreModel", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kinopoisk.Models.MovieInfoModel", "MovieInfo")
                        .WithMany()
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MovieInfo");
                });

            modelBuilder.Entity("Kinopoisk.Models.MovieModel", b =>
                {
                    b.HasOne("Kinopoisk.Models.MovieInfoModel", "MovieInfo")
                        .WithOne("Movie")
                        .HasForeignKey("Kinopoisk.Models.MovieModel", "MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieInfo");
                });

            modelBuilder.Entity("WatchedMovieModel", b =>
                {
                    b.HasOne("Kinopoisk.Models.MovieModel", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kinopoisk.Models.UserModel", "User")
                        .WithMany("watchedMovies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kinopoisk.Models.MovieInfoModel", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("Genres");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Kinopoisk.Models.UserModel", b =>
                {
                    b.Navigation("watchedMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
